### PR TITLE
Support auth method introduced in 6.43

### PR DESCRIPTION
**Pull request by luqasz**

### CODE REVIEW

**Comment by Serphentas** [comment]
As you said in #28 this implies sending the credentials in clear at first, while the router may not necessarily be running 6.43+. Should we use a decoy login to determine the version ?

**Comment by luqasz** [comment]
Yes we can send a decoy user. e.g. `dummy_user` I've pushed my recent changes to this PR.

**Comment by Serphentas** [comment]
Just saw that, looks good. I guess the CI tests make sure the new login code works for both authentication methods ?

**Comment by luqasz** [comment]
>  I guess the CI tests make sure the new login code works for both authentication methods ?

Yes. I've added 6.43 images to fixtures.

**Comment by Serphentas** [comment]
Okay cool, thanks for the PR. I'll test it IRL tomorrow. Still haven't got time to code unfortunately...

**Comment by luqasz** [comment]
@Serphentas any luck with testing ?

**Comment by dejx** [comment]
When could we expect a new release including this?

**Comment by Serphentas** [comment]
@luqasz Sorry for the delay, I've been quite busy these days.

As for testing, I've noticed that when using this version to connect to 6.43 the console says "via winbox" with the expected error for dummy_user but to 6.42 it says "via api". Not sure if this is good or bad.

**Comment by luqasz** [comment]
> As for testing, I've noticed that when using this version to connect to 6.43 the console says "via winbox" with the expected error for dummy_user but to 6.42 it says "via api". Not sure if this is good or bad.

Meh. Irrelevant.

**Comment by luqasz** [comment]
@dejx I've just released 2.1.0

**Comment by dejx** [comment]
Works prefect. Thank you @luqasz

**Comment by luqasz** [comment]
Thx for your input. First of all, we need to figure out a way not to break backwards compatibility (if possible at all). I do not want any one using this library to find out that with a next minor release, their software isn't working.

> For instance I have router monitoring system which log in into router every minute and log is full with this error messages.

Can you filter out those dummy_user logins.

**Comment by Roman-Akopov** [comment]
Thanks for your fast response.

My proposal is that new parameter name is unique and can't be confused with anything. No existing code uses "use_6_43_auth". Google search by this name returns absolutely nothing right now. So you are safe adding this parameter. Also it has default value, so calling code requires no modifications.

Default value is None, not True or False. None corresponds to existing logic. So if calling code will not specify any value for use_6_43_auth parameter, then behavior will not change.

Also I did not find any way to filter out errors for dummy_user in particular.

**Comment by luqasz** [comment]
Ok. I will figure something out.

**Comment by luqasz** [comment]
@Roman-Akopov Can you please create a issue so that our discussion will not get lost. Please link this PR to it.

**Comment by Roman-Akopov** [comment]
Done https://github.com/luqasz/librouteros/issues/38

**Pull request merged**
